trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'AZR'
  azureSubscription: 'azureRM' 
  containerRegistry: 'dersimabbas.azurecr.io'
  functionsImageName: 'cloud-ninja-functions'
  functionAppName: 'ContainerFunctionsTest' 
  AZURE_RESOURCE_GROUP: 'RG-dersimabbas'
  tag: 'latest'  

stages:
- stage: Deploy
  displayName: 'Deploy to az func from container'
  jobs:
  - job:
    displayName: 'Deploy azure functions'
    steps:

    - task: Docker@2
      
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - task: AzureFunctionAppContainer@1
      inputs:
        azureSubscription: 'azureRM'
        appName: 'ContainerFunctionsTest'
        imageName: 'cloud-ninja-functions'
            
     