trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/backend/AzFunctions/CloudNinjaFunctions 

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AZR'  
  containerRegistry: 'dersimabbas.azurecr.io'
  functionsDockerfilePath: 'src/backend/AzFunctions/CloudNinjaFunctions/Dockerfile' 
  functionsImageName: 'cloudNinja-Function'
  tag: 'latest'

stages:
- stage: Build
  displayName: 'Build and Push Azure Functions Docker image'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and push Azure Functions docker image'
    steps:
      - task: Docker@2
        displayName: 'Login to ACR'
        inputs:
          command: login
          containerRegistry: $(azureSubscription)

      - task: Docker@2
        displayName: 'Build and push Azure Functions image'
        inputs:
          command: buildAndPush
          repository: $(functionsImageName)
          dockerfile: $(functionsDockerfilePath)
          containerRegistry: $(azureSubscription)
          context: 'src/backend/AzFunctions/CloudNinjaFunctions'  
          tags: |
            $(tag)
