trigger:
  branches:
    include:
      - main

  paths:
    include:
    - src/frontend/**
    - src/backend/CloudNinjaAPI

pool:
 vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AZR'
  containerRegistry: 'dersimabbas.azurecr.io'
  frontendDockerfilePath: 'src/Frontend/CloudNinjaBlazor/Dockerfile'
  backendDockerfilePath: 'src/Backend/CloudNinjaAPI/Dockerfile'
  frontendImageName: 'frontend'
  backendImageName: 'backend'
  tag: 'latest'

stages:
- stage: Build
  displayName: 'Build and Push Docker image'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and push docker images'
    steps:
      - task: Docker@2
        displayName: 'Login to ACR'
        inputs:
          command: login
          containerRegistry: $(azureSubscription)

      - task: Docker@2
        displayName: 'Build and push'
        inputs:
          command: buildAndPush
          repository: $(frontendImageName)
          dockerfile: $(frontendDockerfilePath)
          containerRegistry: $(azureSubscription)
          tags: |
            $(tag)
            
        
      - task: Docker@2
        displayName: 'Build and push Backend Image'
        inputs:
          command: buildAndPush
          repository: $(backendImageName)
          dockerfile: $(backendDockerfilePath)
          containerRegistry: $(azureSubscription)
          tags: |
            $(tag)
            