trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/Backend/AzFunctions/CloudNinjaFunctions/** 

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AZR'
  containerRegistry: 'dersimabbas.azurecr.io'
  functionsImageName: 'cloud-ninja-Functions'
  tag: 'latest'

stages:
- stage: Build
  displayName: 'Build and Push Azure Functions Docker image'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and push Azure Functions docker image'
    steps:
    

      - task: Docker@2
        displayName: 'Login to ACR'
        inputs:
          command: login
          containerRegistry: $(azureSubscription)

      - task: Docker@2
        displayName: 'Build and push Azure Functions image'
        inputs:
          command: buildAndPush
          repository: $(containerRegistry)/$(functionsImageName)
          dockerfile: 'src/Backend/AzFunctions/CloudNinjaFunctions/Dockerfile'
          containerRegistry: $(azureSubscription)
          buildContext: 'src/Backend/AzFunctions/CloudNinjaFunctions'
          tags: |
            $(tag)
