trigger: none
pr: none

# For newer Azure DevOps versions
resources:
  containers:
    - container: frontend
      image: dersimabbas.azurecr.io/frontend:latest
      type: ACR
      azureSubscription: 'azurerm'
      resourceGroup: 'rg-dersimabbas'
      registry: 'dersimabbas'
      repository: 'frontend'
      trigger: 
        enabled: true
        tags:
          include:
          - latest
    
    - container: backend
      image: dersimabbas.azurecr.io/backend:latest
      type: ACR
      azureSubscription: 'azurerm'
      resourceGroup: 'rg-dersimabbas'
      registry: 'dersimabbas'
      repository: 'backend'
      trigger: 
        enabled: true
        tags:
          include:
          - latest



pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azurerm'
  containerRegistry: 'dersimabbas.azurecr.io'
  webAppName: 'Cloud-NinjaRecon'
  frontendImageName: 'frontend'
  backendImageName: 'backend'
  tag: 'latest'

stages:
- stage: Deploy
  displayName: 'Deploy to web app'
  jobs:
  - job: DeployToWebApp
    displayName: 'Deploy to web app'
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI login'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cat > docker-compose.yml << 'EOF'
          version: '3'
          services:
            frontend:
              image: dersimabbas.azurecr.io/frontend:latest
              ports:
                - "80:80"
              depends_on:
                - backend
            backend:
              image: dersimabbas.azurecr.io/backend:latest
              ports:
                - "5000:80"
          EOF
          
          # Add command to deploy to web app
          az webapp config container set --resource-group rg-dersimabbas --name $(Cloud-NinjaRecon) --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml
