trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azureRM' 
  containerRegistry: 'dersimabbas.azurecr.io'
  functionsImageName: 'cloud-ninja-functions'
  functionAppName: 'CloudNinjaBreacher' 
  AZURE_RESOURCE_GROUP: 'RG-dersimabbas'
  tag: 'latest'  

stages:
- stage: Deploy
  displayName: 'Deploy to az func from container'
  jobs:
  - job:
    displayName: 'Deploy azure functions'
    steps:
      - task: AzureCLI@2
        displayName: 'azure cli deploy'
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: bash
          inlineScript: |
            az functionapp config container set \
              --name $(functionAppName) \
              --resource-group $(AZURE_RESOURCE_GROUP) \
              --docker-custom-image-name $(containerRegistry)/$(functionsImageName):$(tag) \
              --docker-registry-server-url https://$(containerRegistry) \
              --docker-registry-server-managed-identity-enabled true